config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  root 'welcome#main'
  
  get '/results', to: 'welcome#results', as: 'results'
  get '/search', to: 'welcome#search', as: 'search'
  get '/about', to: 'welcome#about', as: 'about'
  get '/help', to: 'welcome#help', as: 'help'
  get '/howto', to: 'welcome#howto', as: 'howto'
  get '/contact', to: 'welcome#contact', as: 'contact'
  get '/termsandconditions', to: 'welcome#termsandconditions', as: 'termsandconditions'
  get '/errors/401', to: 'errors#unauthorized', as: 'errors_401'
  get '/errors/404', to: 'errors#not_found', as: 'errors_404'
  
  resources :skills

  resources :users, except: [:index, :new, :create] do 
    resources :experiences, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end
    
 end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  geocoded_by :location
  after_validation :geocode
  
  has_many :experiences
  has_many :skills, :through => :experiences
  has_many :written_reviews, class_name: "Review", foreign_key: "reviewer_id"
  has_many :reviews, class_name: "Review", foreign_key: "reviewee_id"
  
  has_attached_file :avatar, 
                    :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                    :default_url => "zapskills_platypus.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  before_save :default_values
  
  def default_values
    self.rating ||= 0
  end
  
  def location
    return "#{self.city}, #{self.state}, #{self.zip_code}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :verify_complete_profile, only: [:show]
    
  def index
    @users = User.all
  end

  def show
  end

  def edit
    if !authorize_user(@user)
      redirect_to errors_401_path and return
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
  
  def authorize_user(user)
    user == current_user
  end

  # Use callbacks to share common setup or constraints between actions.
   def set_user
     @user = User.find(params[:id])
   end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :city, :state, :zip_code, :password, :profile_picture_url, :avatar)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

		
	<h1>Update Profile</h1>
	<br \>
  <div class="form-group">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, class: "form-control", required: true %>
  </div>
			
  <div class="form-group">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= f.label :city %><br />
    <%= f.text_field :city, autofocus: true, class: "form-control", required: true %>
  </div>

	<div class="form-group">
    <%= f.label :state %><br>
		<%= f.select :state, options_for_select(us_states, @user.state), required: true %>
	</div>

  <div class="form-group">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code, autofocus: true, class: "form-control", required: true %>
  </div>
	
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class: "btn btn-primary btn-sm" %>
  </div>
	

<% end %>

app/views/users/edit.html.erb
<div class="containter-fluid form-margins">
	<div class="col-md-3"></div>

	<div class="col-md-6">
		<%= render 'form' %>
	</div>

	<div class="col-md-3"></div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Date of birth</th>
      <th>Password</th>
      <th>Profile picture url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip_code %></td>
        <td><%= user.password %></td>
        <td><%= user.profile_picture_url %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<% @title="Profile"%>
<div class="container"> 
	<div class="row">
		<div class="col-sm-10">
			<h1><%= @user.first_name %></h1>
			<br>
		</div>
		<div class="col-sm-2">
			<%= image_tag @user.avatar.url, class: "img-thumbnail pull-left" %>
		</div>
	</div>
	<br>

	<div class="row">
		<div class="col-sm-3">
			<!--left col-->
			<ul class="list-group">
				<li class="list-group-item text-muted" contenteditable="false">Profile</li>
				<li class="list-group-item text-right">
					<strong class="pull-left">Location</strong><%= @user.city %>
				</li>
				<li class="list-group-item text-right">
					<strong class="pull-left">Email </strong><%= mail_to(@user.email) %>
				</li>
				<li class="list-group-item text-right">
					<strong class="pull-left">Rating </strong>
					<!-- Implement the user rating star here. Pretty janky implementation, but whatever. -->
					<% if @user.rating == 0 %>
						No rating yet
					<% else %>
						<!--Get the nearest whole number, while rounding down -->
						<% (@user.rating.to_i/1).times do |i|  %>
							<%= image_tag "full_star.png" %>
						<% end %>
						<!-- If there is a .5, then also add a half star -->
						<% if @user.rating > @user.rating.to_i/1 %>
							<%= image_tag "half_star.png" %>
						<% end %>
					<% end %>
				</li>
				<% if @user == current_user %>
					<li class="list-group-item text-left"><span>
						<strong><%= link_to "Edit", edit_user_path(current_user) %></strong>
					</li>
				<% end %>
			</ul>
		</div> 
		<div class="col-sm-9">
			<div class="panel panel-default">
			<div class="panel-heading">Skills</div>
				<div class="panel-body"> 
					<div class="table-fixed">
						<% if @user.skills.empty? %>
							This user doesn't have any skills yet.<br \>
						<% else %>
							<table class="table table-striped table-hover">
								<thead>
									<tr>
										<th>Subject</th>
										<th>Level</th>
										<th>Description</th>
									</tr>
								</thead>
								<tbody>
									<% @user.experiences.each do |experience| %>
										<tr>
											<td><%= experience.skill.name %></td>
											<td><%= experience.level %></td>
											<td><%= experience.description %></td>
											<% if @user == current_user %>
												<td><%= link_to "Edit Skill", edit_user_experience_path(current_user, experience.id) %></td>
												<td><%= link_to "Delete", user_experience_path(current_user, experience.id), method: "delete" %></td>
											<% end %>
										</tr>
									<% end %>
								</tbody>
							</table>
						<% end %>
						<% if @user == current_user %>
							<%= link_to "Add Skill", new_user_experience_path(current_user) %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		
	</div><!-- /.row -->

	<div class="row">
		<div class="col-sm-3">
		</div>
		<div class="col-sm-9">
			<div class="panel panel-default">
			<div class="panel-heading">Reviews</div>
				<div class="panel-body"> 
					<div class="table-fixed">
						<% if @user.reviews.empty? %>
							No Reviews. 
						<% else %>
							<table class="table table-striped table-hover">
								<thead>
									<tr>
										<th>Subject</th>
										<th>Stars</th>
									</tr>
								</thead>
								<tbody>
									<% @user.reviews.each do |review| %>
										<tr>
											<td><%= review.skill.name %></td>
											<td>
												<% review.stars.times do |i| %>
													<%= image_tag "full_star.png" %>
												<% end %>
											</td>
											<td><%= review.body %></td>
											<% if review.reviewer_id == current_user.id %>
												<td><%= link_to "Edit Review", edit_user_review_path(@user, review.id) %></td>
												<td><%= link_to "Delete Review", user_review_path(@user, review.id), method: "delete" %></td>
											<% end %>
										</tr>
									<% end %>
								</tbody>
							</table>
						<% end%>
						<% if @user != current_user && !@user.skills.empty? %>
							<%= link_to "Add Review", new_user_review_path(@user, current_user) %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>