config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }
  root 'welcome#main'
  
  get '/results', to: 'welcome#results', as: 'results'
  get '/search', to: 'welcome#search', as: 'search'
  get '/about', to: 'welcome#about', as: 'about'
  get '/help', to: 'welcome#help', as: 'help'
  get '/howto', to: 'welcome#howto', as: 'howto'
  get '/contact', to: 'welcome#contact', as: 'contact'
  get '/termsandconditions', to: 'welcome#termsandconditions', as: 'termsandconditions'
  get '/errors/401', to: 'errors#unauthorized', as: 'errors_401'
  get '/errors/404', to: 'errors#not_found', as: 'errors_404'
  
  resources :skills

  resources :users, except: [:index, :new, :create] do 
    resources :experiences, only: [:new, :create, :edit, :update, :destroy]
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end
    
 end

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="container">		
  	<div class="pull-left" id="navigation-container">
			<ul id="navigation">
				<li>Version 0.01</li>
				<li><%= link_to 'About', about_path %></li>
				<li><%= link_to 'Help', help_path %></li>
				<li><%= link_to 'How To', howto_path %></li>
				<li><%= link_to 'Contact', contact_path %></li>
				<li><%= link_to 'Terms and Conditions', termsandconditions_path %></li>
			</ul>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

 			<%= link_to image_tag("zapskills_header_thumbnail.png", style: "  height: 40px; width: auto;"), root_url, class: "navbar-brand"%>
       <ul class="nav navbar-nav">
        <li><h3><%= link_to 'ZapSkills', root_url %></h3></li>
	      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li><%= link_to 'Search', search_path %></li>
						<li><%= link_to 'Profile', user_path(current_user) %></li>
						<li><%= link_to 'Account', edit_user_registration_path(current_user) %></li>
						<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to 'Login', new_user_session_path %></li>
					<% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
						<li><%= link_to 'Contact', contact_path %></li>
						<li><%= link_to 'How To', howto_path %></li>
						<li><%= link_to 'Terms and Conditions', termsandconditions_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= @title %></title>
	
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
	
	<%= favicon_link_tag 'ZapSkills_favicon.png' %>

</head>
<body>
	

	<%= render 'layouts/header' %>
	
	<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>
	<% if alert%>
		<p id="alert"><%= alert %></p>
	<% end %>
	
	<%= yield %>
	

</body>
</html>